### PR TITLE
Show docker hub badge information

### PR DESCRIPTION
**Pull request by darless**
This is useful to see the status as well as be able to go directly to
docker hub.

Additionally I put this information in the Wiki as well. In my opinion all the module information should go there as well as any other custom changes so that the README.md can be a bit more concise to setup.

### CODE REVIEW

**Review by lylepratt — COMMENTED** [review]
I guess you were able to get mod_av to compile properly? Last time I tried I had problems.

**Comment by darless** [comment]
Yes I was able to enable mod_av without any real modifications. For issue #5 I only meant it for the docker hub badge information not for the the other 2 commits, github auto included them in this commit. I should of done this differently.

Until I test out this a bit more I will close this change. The wiki that I created will still contain the badge information until then.

If you know of a fs_cli based originate call that can be used to test mod_av let me know. Just enabling the module in build/modules.conf allowed everything to compile fine.

To explain my other changes:

* systemd service, bashrc, and install-deps changes:
  * Add a systemd service file which adds its own iptables for starting/stopping the docker instance.
    bashrc updated to update PATH so you can run fs_cli once you exec into the docker
  * Update install-deps.sh to use -j`nproc` where needed to speed up those compilations.
* Module mod_av (Related to #1)
  * Just enabled it and it compiled fine.

**Comment by darless** [comment]
I've done the following tests:

1. Setup 2 VMs with docker and started the services as described https://github.com/MadRussian/freeswitch-container/wiki/Running-docker-freeSWITCH-as-a-service-in-16.04 with the vanilla configuration.
2. Tested a basic call via fs_cli originate command via sofia/external
3. Tested a fax inbound/outbound.
4. Had a grandstream SIP client (via android app) register to my testing docker freeswitch.

Re-opening this pull request. Now while I'm not sure how to test the mod_av, it did compile fine.

**Comment by lylepratt** [comment]
thank you @MadRussian for the excellent PR!

**Pull request merged**
